'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/davmre/transformers
  TrainAddition:
    resources:
      instance-type: C4
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: |-
        pip install --upgrade -r /inputs/repo/requirements.txt
        pip install tensorboardX
        pip install -e /inputs/repo/
        cp -R /inputs/repo /transformers
        python /transformers/experiments/addition.py
      image: cwetherill/jax:latest