'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/davmre/transformers
  TrainAddition:
    resources:
      instance-type: C4
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: |-
        pip install --upgrade jax[cuda] -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
        pip install --upgrade -r /inputs/repo/requirements.txt
        pip install tensorboardX
        cp -R /inputs/repo /transformers
        cd /transformers
        pip install -e .
        echo $PYTHONPATH
        export PYTHONPATH=.:$PYTHONPATH
        python experiments/addition.py
      image: cwetherill/jax:latest